# Generated by Django 5.0.6 on 2024-05-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date'], 'verbose_name': 'Articles'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
