# Generated by Django 5.0.6 on 2024-06-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_options_blogpost_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date'], 'verbose_name': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categorie'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
