# Generated by Django 5.0.6 on 2024-06-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpost_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='picture',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
    ]
