# Generated by Django 5.0.6 on 2024-06-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='blog/profile.png', upload_to='blog'),
        ),
    ]
